####################################################################
# PopulationSim Properties
####################################################################


# Algorithm/Software Configuration
# ------------------------------------------------------------------
INTEGERIZE_WITH_BACKSTOPPED_CONTROLS: True
SUB_BALANCE_WITH_FLOAT_SEED_WEIGHTS: False
GROUP_BY_INCIDENCE_SIGNATURE: True
USE_SIMUL_INTEGERIZER: True
USE_CVXPY: False
max_expansion_factor: 100
# note a higher expansion factor was tried, I think the issue is a rounding issue for small zones


# Geographic Settings
# ------------------------------------------------------------------
geographies: [REGION, PUMA, BLOCK]
seed_geography: PUMA


# Tracing
# ------------------------------------------------------------------


  
# Data Directory
# ------------------------------------------------------------------
data_dir: data


# Input Data Tables
# ------------------------------------------------------------------
# input_pre_processor input_table_list
input_table_list:
  - tablename: households
    filename : GQ_seed_households.csv
    index_col: hh_id
    column_map:
      # not sure what SERIALNO is, but it is not unique
      #SERIALNO: hh_id
      hhnum: hh_id
  - tablename: persons
    # expression_filename: seed_persons_expressions.csv
    filename : GQ_seed_persons.csv
    column_map:
      # SERIALNO: hh_id
      hhnum: hh_id
      SPORDER: per_num
    # drop mixed type fields that appear to have been incorrectly generated
    drop_columns:





  - tablename: geo_cross_walk
    filename : geo_cross_walk.csv
  - tablename: BLOCK_control_data
    filename : DecennialBlockData_GQ.csv
 # - tablename: TAZ_control_data
   # filename : tazData.csv
 # - tablename: REGION_control_data
    #filename : control_totals_meta.csv
   # filename : metaData.csv


# Reserved Column Names
# ------------------------------------------------------------------
household_weight_col: GQWGTP
household_id_col: hh_id
total_hh_control: num_hh


# Control Specification File Name
# ------------------------------------------------------------------
control_file_name: GQ_controls.csv


# Output Tables
# ------------------------------------------------------------------
# output_tables can specify either a list of output tables to include or to skip
# if neither is specified, then no tables will be written

output_tables:
  action: include
  tables:
    - summary_BLOCK
   # - summary_TAZ
    - summary_MAZ_PUMA
    - expanded_household_ids


# Synthetic Population Output Specification
# ------------------------------------------------------------------
#

output_synthetic_population:
  household_id: household_id
  households:
    filename: GQ_synthetic_households.csv
    columns:
      - GQWGTP
      - SERIALNO
      - HTYPE
      - NWESR
      - HHINCADJ
      - hhchild
      - NP
      - HINCP
      - TEN
      - BLD
      - ADJINC
      - VEH
      - HHT
      - TYPE
      - NPF
      - HUPAC
      - GQFLAG
      - GQTYPE      
      
  persons:
    filename: GQ_synthetic_persons.csv
    columns:
      - gqwgtp
      - SERIALNO
      - employed
      - soc
      - OCCP
      - AGEP
      - SEX
      - WKHP
      - ESR
      - SCHG
      - WKW
      - MIL
      - SCHL
      - per_num
      - GQFLAG


# Steps for base mode
# ------------------------------------------------------------------
run_list:
  steps:
    - input_pre_processor
    - setup_data_structures
    - initial_seed_balancing
    - meta_control_factoring
    - final_seed_balancing
    - integerize_final_seed_weights
    #- sub_balancing.geography=TAZ
    - sub_balancing.geography=BLOCK
    - expand_households
    - summarize
    - write_tables
    - write_synthetic_population

  #resume_after: expand_households
