####################################################################
# PopulationSim Properties
####################################################################


# Algorithm/Software Configuration
# ------------------------------------------------------------------
INTEGERIZE_WITH_BACKSTOPPED_CONTROLS: True
SUB_BALANCE_WITH_FLOAT_SEED_WEIGHTS: False
GROUP_BY_INCIDENCE_SIGNATURE: True
USE_SIMUL_INTEGERIZER: True
USE_CVXPY: False
max_expansion_factor: 30


# Geographic Settings
# ------------------------------------------------------------------
geographies: [REGION, PUMA, TRACT, BG, BLOCK]
seed_geography: PUMA


# Tracing
# ------------------------------------------------------------------


  
# Data Directory
# ------------------------------------------------------------------
data_dir: data


# Input Data Tables
# ------------------------------------------------------------------
# input_pre_processor input_table_list
input_table_list:
  - tablename: households
    filename : GP_seed_households.csv
    index_col: hh_id
    column_map:
      hhnum: hh_id
  - tablename: persons
    filename : GP_seed_persons.csv
    column_map:
      hhnum: hh_id
      SPORDER: per_num
    # drop mixed type fields that appear to have been incorrectly generated
    drop_columns:
    
  - tablename: geo_cross_walk
    filename : geo_cross_walk.csv
  - tablename: BLOCK_control_data
    filename : GP_BlockData.csv
  - tablename: BG_control_data
    filename : GP_BGData.csv
  - tablename: TRACT_control_data
    filename : GP_TRACTData.csv
#  - tablename: REGION_control_data
    #filename : control_totals_meta.csv
#    filename : GP_metaData.csv


# Reserved Column Names
# ------------------------------------------------------------------
household_weight_col: WGTP
household_id_col: hh_id
total_hh_control: num_hh


# Control Specification File Name
# ------------------------------------------------------------------
control_file_name: GP_controls.csv


# Output Tables
# ------------------------------------------------------------------
# output_tables can specify either a list of output tables to include or to skip
# if neither is specified, then no tables will be written

output_tables:
  action: include
  tables:
    - summary_BLOCK
    - summary_BG
    - summary_TRACT
    - expanded_household_ids


# Synthetic Population Output Specification
# ------------------------------------------------------------------
#

output_synthetic_population:
  household_id: household_id
  households:
    filename: GP_synthetic_households.csv
    columns:
      - WGTP
      - SERIALNO
      - HTYPE
      - NWESR
      - HHINCADJ
      - hhchild
      - NP
      - HINCP
      - TEN
      - BLD
      - ADJINC
      - VEH
      - HHT
      - TYPE
      - NPF
      - HUPAC
      
      
  persons:
    filename: GP_synthetic_persons.csv
    columns:
      - wgtp
      - SERIALNO
      - employed
      - soc
      - OCCP
      - AGEP
      - SEX
      - WKHP
      - ESR
      - SCHG
      - WKW
      - MIL
      - SCHL
      - per_num
      


# Steps for base mode
# ------------------------------------------------------------------
run_list:
  steps:
    - input_pre_processor
    - setup_data_structures
    - initial_seed_balancing
#    - meta_control_factoring
    - final_seed_balancing
    - integerize_final_seed_weights
    - sub_balancing.geography=TRACT
    - sub_balancing.geography=BG
    - sub_balancing.geography=BLOCK
    - expand_households
    - summarize
    - write_tables
    - write_synthetic_population

  #resume_after: expand_households
